export const MCHAT_QUESTIONS = [
  {
    id: 1,
    question: 'If you point at something across the room, does your child look at it?',
    question_ur: 'اگر آپ کمرے میں کسی چیز کی طرف اشارہ کریں، تو کیا آپ کا بچہ اسے دیکھتا ہے؟',
    type: 'yes_no',
    critical: true,
    domain: 'social',
  },
  {
    id: 2,
    question: 'Have you ever wondered if your child might be deaf?',
    question_ur: 'کیا آپ نے کبھی سوچا ہے کہ شاید آپ کا بچہ بہرا ہو؟',
    type: 'yes_no',
    critical: false,
    domain: 'communication',
  },
  {
    id: 3,
    question: 'Does your child play pretend or make-believe?',
    question_ur: 'کیا آپ کا بچہ بناوٹی یا تخیلاتی کھیل کھیلتا ہے؟',
    type: 'yes_no',
    critical: true,
    domain: 'social',
  },
  {
    id: 4,
    question: 'Does your child like climbing on things?',
    question_ur: 'کیا آپ کا بچہ چیزوں پر چڑھنا پسند کرتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'motor',
  },
  {
    id: 5,
    question: 'Does your child make unusual finger movements near his/her eyes?',
    question_ur: 'کیا آپ کا بچہ اپنی آنکھوں کے قریب انگلیوں کی غیر معمولی حرکات کرتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'behavior',
  },
  {
    id: 6,
    question: 'Does your child point with one finger to ask for something or to get help?',
    question_ur: 'کیا آپ کا بچہ کسی چیز کے لیے مانگنے یا مدد لینے کے لیے ایک انگلی سے اشارہ کرتا ہے؟',
    type: 'yes_no',
    critical: true,
    domain: 'communication',
  },
  {
    id: 7,
    question: 'Does your child point with one finger to show you something interesting?',
    question_ur: 'کیا آپ کا بچہ آپ کو کوئی دلچسپ چیز دکھانے کے لیے ایک انگلی سے اشارہ کرتا ہے؟',
    type: 'yes_no',
    critical: true,
    domain: 'communication',
  },
  {
    id: 8,
    question: 'Is your child interested in other children?',
    question_ur: 'کیا آپ کا بچہ دوسرے بچوں میں دلچسپی رکھتا ہے؟',
    type: 'yes_no',
    critical: true,
    domain: 'social',
  },
  {
    id: 9,
    question: 'Does your child show you things by bringing them to you or holding them up for you to see?',
    question_ur: 'کیا آپ کا بچہ آپ کو چیزیں لا کر یا اوپر اٹھا کر دکھاتا ہے؟',
    type: 'yes_no',
    critical: true,
    domain: 'communication',
  },
  {
    id: 10,
    question: 'Does your child respond to his/her name when you call?',
    question_ur: 'کیا آپ کا بچہ اپنا نام پکارنے پر جواب دیتا ہے؟',
    type: 'yes_no',
    critical: true,
    domain: 'communication',
  },
  {
    id: 11,
    question: 'When you smile at your child, does he/she smile back at you?',
    question_ur: 'جب آپ اپنے بچے پر مسکراتے ہیں، تو کیا وہ واپس مسکراتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'social',
  },
  {
    id: 12,
    question: 'Does your child get upset by everyday noises?',
    question_ur: 'کیا آپ کا بچہ روزمرہ کی آوازوں سے پریشان ہو جاتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'behavior',
  },
  {
    id: 13,
    question: 'Does your child walk?',
    question_ur: 'کیا آپ کا بچہ چلتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'motor',
  },
  {
    id: 14,
    question: 'Does your child look you in the eye when you are talking to him/her, playing with him/her, or dressing him/her?',
    question_ur: 'کیا آپ کا بچہ بات کرتے، کھیلتے یا کپڑے پہناتے وقت آپ کی آنکھوں میں دیکھتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'social',
  },
  {
    id: 15,
    question: 'Does your child try to copy what you do?',
    question_ur: 'کیا آپ کا بچہ آپ کی نقل کرنے کی کوشش کرتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'social',
  },
  {
    id: 16,
    question: 'If you turn your head to look at something, does your child look around to see what you are looking at?',
    question_ur: 'اگر آپ کسی چیز کو دیکھنے کے لیے سر موڑیں، تو کیا آپ کا بچہ دیکھتا ہے کہ آپ کیا دیکھ رہے ہیں؟',
    type: 'yes_no',
    critical: false,
    domain: 'social',
  },
  {
    id: 17,
    question: 'Does your child try to get you to watch him/her?',
    question_ur: 'کیا آپ کا بچہ آپ کو اسے دیکھنے پر مجبور کرنے کی کوشش کرتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'communication',
  },
  {
    id: 18,
    question: 'Does your child understand when you tell him/her to do something?',
    question_ur: 'کیا آپ کا بچہ آپ کی ہدایات کو سمجھتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'communication',
  },
  {
    id: 19,
    question: 'If something new happens, does your child look at your face to see how you feel about it?',
    question_ur: 'جب کچھ نیا ہو، تو کیا آپ کا بچہ آپ کا چہرہ دیکھتا ہے کہ آپ کیسا محسوس کر رہے ہیں؟',
    type: 'yes_no',
    critical: false,
    domain: 'social',
  },
  {
    id: 20,
    question: 'Does your child like movement activities?',
    question_ur: 'کیا آپ کا بچہ حرکت کی سرگرمیاں پسند کرتا ہے؟',
    type: 'yes_no',
    critical: false,
    domain: 'motor',
  },
]

export const SENSORY_QUESTIONS = [
  { id: 1, question: 'Does your child cover their ears to block out sounds?', domain: 'auditory' },
  { id: 2, question: 'Is your child bothered by certain clothing textures?', domain: 'tactile' },
  { id: 3, question: 'Does your child seek out spinning or swinging activities?', domain: 'vestibular' },
  { id: 4, question: 'Is your child sensitive to bright lights or certain visual patterns?', domain: 'visual' },
  { id: 5, question: 'Does your child have strong reactions to certain smells?', domain: 'olfactory' },
  { id: 6, question: 'Is your child a very picky eater based on food textures?', domain: 'gustatory' },
  { id: 7, question: 'Does your child seek deep pressure (tight hugs, heavy blankets)?', domain: 'proprioceptive' },
  { id: 8, question: 'Does your child seem unaware of pain or temperature?', domain: 'interoceptive' },
]

export const THERAPY_DOMAINS = [
  { value: 'communication', label: 'Communication', icon: '💬' },
  { value: 'social', label: 'Social Skills', icon: '👥' },
  { value: 'behavior', label: 'Behavior', icon: '🧠' },
  { value: 'adaptive', label: 'Adaptive Skills', icon: '🛠️' },
  { value: 'academic', label: 'Academic', icon: '📚' },
  { value: 'motor', label: 'Motor Skills', icon: '🏃' },
  { value: 'emotional', label: 'Emotional Regulation', icon: '❤️' },
]

export const COMMUNICATION_LEVELS = [
  { value: 'nonverbal', label: 'Nonverbal', description: 'Does not use words' },
  { value: 'single_words', label: 'Single Words', description: 'Uses individual words' },
  { value: 'two_word_phrases', label: 'Two-Word Phrases', description: 'Combines two words' },
  { value: 'simple_sentences', label: 'Simple Sentences', description: '3-5 word sentences' },
  { value: 'conversational', label: 'Conversational', description: 'Full conversations' },
]

export const SUBSCRIPTION_TIERS = {
  free: {
    name: 'Free',
    price: 0,
    features: [
      '1 child profile',
      'Basic screening (M-CHAT-R)',
      '5 AI coach messages/month',
      'Basic activity library',
      'Daily journal',
    ],
  },
  basic: {
    name: 'Basic',
    price: 19,
    features: [
      '2 child profiles',
      'All screenings',
      '50 AI coach messages/month',
      'Full activity library',
      'Goal tracking',
      'Progress dashboard',
      'Daily/weekly plans',
    ],
  },
  pro: {
    name: 'Pro',
    price: 49,
    features: [
      'Unlimited children',
      'Unlimited AI coach',
      'All features',
      'Behavior analysis',
      'Parent Training Academy',
      'Digital Autism Passport',
      'Professional marketplace',
      'Priority support',
    ],
  },
  clinic: {
    name: 'Clinic',
    price: 199,
    features: [
      'Everything in Pro',
      'Multiple therapist accounts',
      'Client management',
      'Progress reports',
      'Custom branding',
      'API access',
      'Dedicated support',
    ],
  },
}

export const TRAINING_CATEGORIES = [
  'Autism Basics',
  'ABA Fundamentals',
  'Home Speech Therapy',
  'Occupational Therapy Basics',
  'Behavior Management',
  'School Readiness',
  'Sibling Support',
  'Self-Care Strategies',
]

export const KNOWLEDGE_CATEGORIES = [
  'Autism Basics',
  'Assessments & Diagnosis',
  'Therapies',
  'Education & School',
  'Behavior',
  'Sleep',
  'Feeding & Nutrition',
  'Social Skills',
  'Communication',
  'Family & Caregiving',
]

export const DISCLAIMER = 'MBT is not a substitute for professional diagnosis, treatment, or medical advice. Always consult qualified healthcare professionals for your child\'s care.'
